# Generated by Django 5.0.3 on 2024-04-04 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('timeZoneOffset', models.CharField(max_length=50)),
                ('coordinates', models.CharField(max_length=50)),
                ('temperatureLandSurface', models.DecimalField(decimal_places=2, max_digits=5)),
                ('temperatureSeaSurface', models.DecimalField(decimal_places=2, max_digits=5)),
                ('humidity', models.DecimalField(decimal_places=2, max_digits=5)),
                ('windSpeed', models.DecimalField(decimal_places=2, max_digits=5)),
                ('windDirection', models.CharField(max_length=50)),
                ('precipitation', models.DecimalField(decimal_places=2, max_digits=5)),
                ('haze', models.DecimalField(decimal_places=2, max_digits=5)),
                ('notes', models.TextField()),
            ],
        ),
    ]
