# Generated by Django 5.0.4 on 2024-04-29 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0002_rename_coordinates_observation_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='coordinate_latitude',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='observation',
            name='coordinate_longitute',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='observation',
            name='humidity',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
