# Generated by Django 5.0.4 on 2024-04-29 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0004_alter_observation_coordinate_latitude_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='observation',
            old_name='coordinate_longitute',
            new_name='coordinate_longitude',
        ),
    ]
